[package]
name = "encrypt_file"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm-siv = { version = "0.11.1", features = ["std"] }
rand = "0.8.5"
